### ISSUE TITLE
'Connector_Web' object has no attribute 'map_id'

### ISSUE THREAD

**Issue by chandrasekarkesavan** [opensemanticsearch/open-semantic-search#1]
Can you please let me know where I'm doing mistake?

I'm trying to get the index for web page by passing the URI. I'm getting the error as  'Connector_Web' object has no attribute 'map_id'. Is this because of missing any package or dependency version issue?

![screenshot-69 46 26 106 2016-06-14 16-56-57](https://cloud.githubusercontent.com/assets/11470898/16041138/7b7ae022-3251-11e6-968d-b407bb8aa936.png)

**Comment by opensemanticsearch** [comment]
Mapping id's like URI and filenames is done by an external and much more flexible and changeable plugin, which was not active in your config. Try new and enhanced ETL version which will be released soon with much better error handling, so that such problems won't break processing anymore (first beta released yesterday).
