### ISSUE TITLE
Comment on highlighted search words instructions.

### ISSUE THREAD

**Issue by memoday** [opensemanticsearch/open-semantic-search#10]
Hi support team,

I believe there is something wrong at this page https://www.opensemanticsearch.org/doc/admin/config/stemming

under "Change the language / grammar", it reads:

and to be able to highlight searched words in the snippets even if written in other form change

...
`<field name="content" type="text_en" indexed="false" stored="true" multiValued="true"/>
`...

to

...
`<field name="content" type="text_de" indexed="false" stored="true" multiValued="true"/>`

I don't see any difference here except for the type "en vs. de'. How is this supposed to highlight words that are stemmed from the searched word even if't is not identical to the search term? 

Please feel free to delete this post if I am wrong.

Thanks

**Comment by opensemanticsearch** [comment]
text_de or text_en are Solr fields set to a language specific stemmer or stemming configuration with other language parameters.

The search UI uses the field "content" for highlighting snippet parts if same words like query. 

If this field is configured to the used stemming configuration, the highlighting component will highlight other word forms like "searching" if you search for "search", which could not happen if for example you use no stemmer for this field or another stemming configuration like german (de) because in german there is no -ing suffix like in english (en).
