### ISSUE TITLE
How enable the User Interface for a bidi language?

### ISSUE THREAD

**Issue by memoday** [opensemanticsearch/open-semantic-search#11]
Hi admin,

I see that you can either switch between English or German. What if I want to have the interface in Arabic and make the whole layout RTL? What should I do and which files should be modified?

Thanks,

**Comment by opensemanticsearch** [comment]
RTL means right to left?

We'll decide/evaluate to use a more professional internationalization infrastructure/libraries first week of december, when it's clear if a customer will order a full internationalized german version or another customer an arabic version (then because RTL you or i'll have a closer look to the CSS framework Zurb Foundation we use).

If someone wants to translate UIs to another language than german or english earlier please let us know, so we can manage all strings on a better to handle language file format earlier (maybe a RDF graph for all strings with language tags for labels and exporting them to the frameworks standard formats or use directly standard PO files as base with django.utils.translation for Django).

**Comment by memoday** [comment]
Yes, I meant right to left. I can help with translation from English into Arabic. A PO file would be fine with me.

Thanks for creating such a great project.
