### ISSUE TITLE
Cannot delete a file from index.

### ISSUE THREAD

**Issue by arkxdns** [opensemanticsearch/open-semantic-search#128]
I cannot delete a file from index. I used the following command : **opensemanticsearch-delete file:///directory/file** but nothing, the file is still there.

Thanks for any help.

**Comment by dhyams** [comment]
I've had some of the same problem, but only because I was using the incorrect URI.  Even if you insert the file with the full path, you have the use the same URI that OpenSemanticSearch would use in order to delete the entry from your database.  The URI is subject to any mappings you may have put in /etc/opensemanticsearch/etl.

**Comment by dhyams** [comment]
This is related to

**Comment by dhyams** [comment]
https://github.com/opensemanticsearch/open-semantic-etl/issues/19

**Comment by Mandalka** [comment]
Now you can use the file system filename instead of mapped URI, too.

Implemented support of filenames (and its mapping config) in etl_delete.py (opensemanticsearch-delete) by https://github.com/opensemanticsearch/open-semantic-etl/commit/6b37bca310021abe09a1bfffcb651ec45f63c6b8.
