### ISSUE TITLE
Is there a way to install this on fedora without a VM?

### ISSUE THREAD

**Issue by dangbert** [opensemanticsearch/open-semantic-search#149]
Like is there a way to build this from source?  It seems that only debian files are provided which aren't fedora compatible (to the best of my knowledge).

**Comment by opensemanticsearch** [comment]
Not by an out of the box package.

There are many dependencies, which are defined by the deb packages (in configfile control) and so installed automatically by Debian or Ubuntu and additional ones which are installed by pip (added pip calls in postinst scripts).

If all that dependencies are installed it could be possible from sources, since all are interprated scripts based on Python, Django, Solr (Java), Tika and PHP.

The Solr installer should be ranable on Fedora, too.

**Comment by opensemanticsearch** [comment]
Maybe coming docker containers will be easier alternate to run it on Fedora.
