### ISSUE TITLE
Filesystem monitoring *.deb install fails on Ubuntu Xenial 

### ISSUE THREAD

**Issue by marbetschar** [opensemanticsearch/open-semantic-search#15]
I'm trying to install the filesystem monitoring *.debs on Ubuntu Xenial, but I receive the following error message:

```
opensemanticsearch-trigger-filemonitoring : Depends: opensemanticsearch-connector-files (>= 0)
but it is not installable
```

What am I'm doing wrong?

FWIW here are all setup steps done on this server:

```
sudo apt install ./open-semantic-search-server-ubuntu_xenial_16.10.10.deb
sudo apt-get install unoconv
sudo apt install ./opensemanticsearch-trigger-filemonitoring_15.06.26_all.deb
...
opensemanticsearch-trigger-filemonitoring : Depends: opensemanticsearch-connector-files (>= 0)
but it is not installable
```

**Comment by opensemanticsearch** [comment]
Tnx for your info. It is this issue: https://github.com/opensemanticsearch/open-semantic-search/issues/7

Please let this issue open, so i will upload with next version and will close it, when done.

**Comment by marbetschar** [comment]
Good news! Any approx ETA?

**Comment by marbetschar** [comment]
Anything in terms of an ETA?

**Comment by opensemanticsearch** [comment]
New releases planned in two weeks, when the SKOS integration (see other issue) is fully implemented.

**Comment by marbetschar** [comment]
@opensemanticsearch any news about the new release?

**Comment by opensemanticsearch** [comment]
Because of additional and priorized other features for an customer the release will be this week.

But not sure, if the upgrade to Python 3 is done till then, so the [Django encoding issue](https://github.com/opensemanticsearch/open-semantic-search-appliance/issues/4) will affect you on file monitoring if you have files with special chars in the filename until the upgrade to Python 3 is done or you manipulate your Django 2.x distribution code as workaround.

**Comment by opensemanticsearch** [comment]
Since newer version of local file monitoring component writes directly to the Celery queue instead using the REST-API, the problem with special file names / the charset should be even solved before the planned [upgrade to Python 3](https://github.com/opensemanticsearch/open-semantic-search/issues/21).

The new packages will be available for download on monday or tuesday.

**Comment by Mandalka** [comment]
New (beta) version of local file monitoring code now doing now (batched) parallel processing of as many files at once as you have processors and compatible with Ubuntu LTS is moved to Github and now part of the open-semantic-etl repository and package.

New Debian/Ubuntu packages will follow today or tomorrow with new Open Semantic Search version.

The new user "opensemanticetl" must have read access to monitored files to be able to index them.
