### ISSUE TITLE
no data export to Neo4J

### ISSUE THREAD

**Issue by ronaldoviber** [opensemanticsearch/open-semantic-search#152]
on a fresh debian stretch: there is no export of entities to neo4j.

Version: open-semantic-search_18.12.23

already installed: py2neo + export_neo4j, and activated by config!

no logs, something missing?

**Comment by opensemanticsearch** [comment]
Which version/relase do you use (VM, Deb? only ETL?)? 

Are there Entities defined by Thesaurus or Ontology?

Or/and is NER by machine learning active (UI > Config > NER)?

Is export to Neo4j active in UI -> Config -> Neo4j ?

If disabled there in the Admin UI, the plugin config of Neo4j export in ETL config files will be overwritten / disabled.

Begin of next year the Neo4j export will be extended to work with IDs for entities instead of (only) labels.

**Comment by ronaldoviber** [comment]
thanks for reply

- no Thesaurus/Ontology are defined, just out of the box with some website crawls
- its activated in the UI: spacy NER
- export to neo is also activated in the UI
- also in the etl-config the export is activated
-------------------------------------------------------
i just remember this function export to neo from a earlier version (i think ~april this year) where all entities where exported to neo by default.

In this version i recognice that the shebang in py2neo guide to python (->2.7 vs python3) and in version 2.7 the is no py2neo installed by the install script out of the .deb
But nothing changed after install the ext in 2.7

It seems it´s not triggered

**Comment by opensemanticsearch** [comment]
Will check / upgrade / migrate to newest releases by https://github.com/opensemanticsearch/open-semantic-etl/issues/76

**Comment by ptmaroct** [comment]
Dear why is this marked closed

**Comment by ptmaroct** [comment]
Hello, I have figured it out. This issue is due to dependency version mismatch between py2neo. In the build script, pip3 install py2neo installs the latest version of py2neo, which is v4. There might be some breaking change in the API and because of that, the export functionality is broken.

What I did was uninstall py2neo dependency,

`$ pip3 uninstall py2neo
`
And installed last stable v3 dependency

`$ pip3 install py2neo==3.1.2
`
Kudos! All good now and export works flawlessly.
I have also created a pull request for the same so please accept it!

**Comment by opensemanticsearch** [comment]
Merged https://github.com/opensemanticsearch/open-semantic-etl/pull/77 until upgrade to newest Neo4j and Py2Neo by issue https://github.com/opensemanticsearch/open-semantic-etl/issues/76 in Open Semantic ETL.

**Comment by Mandalka** [comment]
I upgraded to newest Neo4j and the new py2neo 4 seems to work with the py2neo lib instead of underlaying Neo4j Driver for Python, so i changed the pip3 install to use py2neo 4 again.

Maybe for upgrading you need to
pip3 uninstall py2neo
first if yet pinned to version 3.x

Maybe the DB format changed, so Neo4j db has to be deleted like described in #70.

Please reopen (or i will if further tests on fresh debian will cause problems) if yet problems after upgrade to Neo4j 3.5.2 and Py2neo 4.x and newest Open Semantic ETL.

**Comment by Mandalka** [comment]
Since doesn't work on fresh Debian pinned again to py2neo 3.x until upgrade when migrate to new ID/URI instead string based entities in Neo4j.
