### ISSUE TITLE
Demo and Questions?

### ISSUE THREAD

**Issue by lonnieOST** [opensemanticsearch/open-semantic-search#158]
Hello,

We are  researching the current state of the industry for Open Source Search Engines and while searching around, I came across your "Open Semantic Search" engine which might be a possible candidate for us to start with and test out.

To that end, I was wondering if it is Enterprise level in terms of stability, scalability, and expandability. In looking over your main site it looks to be able to have plugins for many diverse data sources which is something that I really need as well, but if you could please tell me about the scalability and stability then that would be helpful.

I am thinking that it might be useful to use it with an Elasticsearch cluster for the data store as well.

Lastly, I was looking for a "Demo" online somewhere, Docker container, or perhaps a video that I could see it in action.

Cheers :)

**Comment by mosea3** [comment]
Hi Ionnie, 
Maybe Markus Mandalka can elighten you more as he is the founder of this project.
I just stumbled upon it 2 years ago and been using this ever since.

I did this research too on Search Engines, but with more wider search terms: basically, an affordable private search engine, a sucessor for Google Search Appliance for companies.

I implemented Open Semantic Search in my company and added some integration features, which at the moment is not (yet?) part of the OSS project.

Background: My company is in metal treatment, we basically want to find information fast as we scan all our stuff into PDFs and I provide Intranet web services to look through (call logs, emails, workflow descriptions, intranet sites, machine status). Currently, 30 users access OSS and we have 30 000 Docs indexed with est. half a million pages.
Our CEO is very proud of having such a good search engine, he usually shows them to external visitors. Another visiting company was so convinced about this solution, they wanted to have it installed as well.

OSS consists of a few parts: the Solr Core/or now also neo4j, storing all docs.
The Indexing is coordinated with a web-managed scheduler for different datasources. 
Google Tesseract does optional OCR on documents.
Apache Tika extracts the metadata and puts them into the DB.

A Web UI, solr-php-ui, is delivered for end user search querys, following basic Search Engine Operators. It can be optimized (vocabulary, ontologies, etc.) for desired languages. This UI is written in PHP, while the Management is done using Django Framework on python.

Key spots for scalability:
- using mounted external storage (we: high availability cluster NAS/SAN)
- using redundant Solr or neo4j servers as a Cluster 
- Make Search UI high available: just use a Web Server Load Balancer (f. ex on Apache, or PHP module)
 
The most important part of this project, I think, is the eager developer community developing, testing, translating and releasing this as package and deployable appliances.

For us as a SMB, OSS is one of the most robust IT Services (less than a few minutes downtime per year), yet: I think its well-suited for much more larger scaled operations.

In what kind of Demo or Screenshots are you interested in?
If more questions regarding my Integration specifically, you can reach out to me directly ;)

In case I didn’t describe OSS accordingly, please forgive me and I will correct this :)

best regards from Switzerland

Andy
Von meinem iPad gesendet

**Comment by lonnieOST** [comment]
Hi Andy,

I hope that you are doing well today and sincerely thank you for going into details in describing your setup as well and use case. It sounds like you have a solid system and it is really working well for you.

You have cleared up a number of questions that I have had relative towards the project that we are building.

Regarding OSS, I am particular interested in working it towards these factors, in no particular order of importance.

1. Docker container --- I have been able to run the Virtualbox VM for the Open Semantic Search Engine and it works well. We use Docker containers so that we can easily replicate and move them from different servers as needed.

2. Elasticsearch backed --- In reading over the OSS documentation, it seems to suggest that OSS can use Apache Solr or Elasticsearch as its backend store. What I would like to do is to have it talk to an external Elasticsearch cluster as we can easily scale the cluster by simple adding more Elasticsearch docker nodes and balancing across servers.

3. OSS Connectors --- I am VERY impressed with what I have read regarding the OSS connectors in that it seems to offer a HUGE versatility and scope. Actually, that along with the Elasticsearch backend data store are the main features that are driving my interest in possible using OSS as the core of our project. What I need, in regards to an OSS connector is this. I have an external type of metasearch engine that can be sent a "user query" for which it will collect website results and return them in an aggregated list in JSON format.  I need for OSS to be able to call this external server and get the results back for which it would store then results in its own Elasticsearch database cluster as well as to send those results back to the user frontend on the main page. This way, when another "similar" user query arrives then it will take the existing results from within its own Elasticsearch database and aggregate them with any new results coming from the external search engine metaserver like before and then storing them as well as returning them to the user. This whole setup would act as a "caching" web server in a sense.

Speed, and stability is also a concern, but the basic tests that I have done seems to show very responsive calls and returns for OSS.  This is important since the project will need to be able to handle many thousands of requests and a growing user load.

These additional factors had made me start looking at a few other projects which also have a number of nice features as well, but I had not been completely satisfied with their core setups and most of them would require a significant amount of time in development to change/modify core functionality towards getting it work as I need for this project:

https://www.opensemanticsearch.org/
https://fess.codelibs.org/
https://www.datafari.com/en/index.html
http://www.opensearchserver.com/
https://yacy.net/en/index.html

Of course, there will be a number of different additional additions as well, but if I am correct, then I think that OSS should be able to do these things and if so, then there might be a great possibility to use it as a starting point and work closely with people like yourself and Markus Mandalka to try to bring it all together as a first step and grow both my project and the OSS development effort as we proceed.

Thanks again and I also thank you for offer to allow me to reach out to you as well, for which I will be doing very shortly so that we can talk in more detail as to what I am doing.

Very best regards from Maryland, USA
Lonnie

**Comment by lonnieOST** [comment]
Thanks for the information and I have been able to run the demo now.

Looks GREAT !!!!

Is there a Dockerfile to build a container?
How can I use a Elasticsearch cluster instead of Apache Solr?

Thanks :)
