### ISSUE TITLE
Problem while installing

### ISSUE THREAD

**Issue by rusty9283** [opensemanticsearch/open-semantic-search#179]
Hello,

while installing this command is showing:
`Starting opensemanticsearch daemon...Checking if and waiting until Tika is up ......`

And then nothing - i was waiting about an hour and then i canceled.
Could someone help me please?

THANKS!

**Comment by opensemanticsearch** [comment]
How did you install? Using the deb or from source (is Tika installed?) ? On which operating system?

Was this an upgrade ? There is a problem (yet) on upgrades, if not killing the Tika daemon and Tika manually.

**Comment by rusty9283** [comment]
I set up an win10 subsystem and installed ubuntu.
Then I tried to install "Open Semantic Search Server (Package)".
The SOLR site works but installing stoped with the command:
`Starting opensemanticsearch daemon...Checking if and waiting until Tika is up ......`
Should i try to install tika?
THANKS!

**Comment by opensemanticsearch** [comment]
Thanks for your report, it's a bug in current release which occurs if Tika was not installed yet before (which will be done automaitcally by the installer) and which will be fixed in todays release.

**Comment by Mandalka** [comment]
Fixed, the dependency Tika service will be installed automatically before starting the ETL daemon. Please reopen issue, if still happens with todays release which will be available for download at evening.

**Comment by rusty9283** [comment]
Hello,
I tried the new version but now i get this failure:
```
Setting up open-semantic-search (19.05.19) ...
The system user `tika' already exists. Exiting.
daemon: fatal: failed to find pid for tika: No such file or directory
dpkg: error processing package open-semantic-search (--configure):
 installed open-semantic-search package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 open-semantic-search
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I hope you can hlep me please.

**Comment by StoltHD** [comment]
This is still a problem under WSL 2, WSL use WSL INIT (PID 1) and systemd can't run the process as long as it is not the init system...

Setting up open-semantic-search (19.05.22) ...
The system user `tika' already exists. Exiting.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
dpkg: error processing package open-semantic-search (--configure):
 installed open-semantic-search package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 open-semantic-search
E: Sub-process /usr/bin/dpkg returned an error code (1)

.................................

  PID TTY          TIME CMD
    1 ?        00:00:00 init
  649 ?        00:00:41 java
 1238 ?        00:00:00 init
 1239 ?        00:00:00 init
 1240 pts/0    00:00:00 bash
 1714 pts/0    00:00:00 ps
18544 ?        00:00:00 init

................................

This is on a debian 10 WSL 2, installed with the latest Semantic Search Server .deb file (19.07.19), since Hyper-V doesn't support OVA files, and it's still problems running Virtualbox on a hyper-v enabled Windows 10 Computer...

Is it possible to get the installer to depend on another system than systemd ? or maybe if its possible for Dev the best option would be to provide some VHD or VHDX images to download...?

At the moment I can not get Open Semantic Search to run nor uninstall it again with APT on WSL...
...........................

**Comment by ZeroCool940711** [comment]
Guys, I know this is an old issue but, is there any news on this?
I tried to install it on WSL and it didn't work for me, got the same error about `systemd` as the last comment here made by @StoltHD ,is there any way to run Open Semantic Search on Windows?
