### ISSUE TITLE
Open Semantic Search for CENTOS?

### ISSUE THREAD

**Issue by rusty9283** [opensemanticsearch/open-semantic-search#182]
Hello!
We use CENTOS in our company - is it also possible to install the Open Semantic Search Server (Package) to this centos server?

Many thanks!

**Comment by baerbock** [comment]
Use a better company.

**Comment by ronnbcnews** [comment]
+1

**Comment by Mandalka** [comment]
Yet no projects or experience on Centos.

Solr may be installable by the Solr installer.

Is the Python 3 package manager PIP available in Centos (how is the name of command? For example in Debian its pip3 because pip is used by older Python2 package manager)?

If yes (and if the apache/php config is not very different to Debian), after https://github.com/opensemanticsearch/open-semantic-search/issues/193 it should become easier to install on Centos (the main problem are many dependencies and lack of many packages in distribution specific repos which many of them after that can be resolved automatically).

**Comment by Mandalka** [comment]
Since to manage all the dependencies and versions (meanwhile better documented in https://github.com/opensemanticsearch/open-semantic-search/blob/master/README.md#dependencies) on more OS than Debian and Ubuntu is a dependency hell,
IMHO best way on other platforms is to use the Docker images (coming soon by #390).
