### ISSUE TITLE
problem while indexing - indexing stopped

### ISSUE THREAD

**Issue by rusty9283** [opensemanticsearch/open-semantic-search#187]
Hello!
I tried to index a network folder with about 2million files with:
opensemanticsearch-index-dir /media/folder/

after about 3 hours it stops.
THe last line is:
"indexing new file /media/folder/...." and nothing happens

Now i tried to delete the index and tried indexing again but now it comes only one line with "indexing new file /media/folder/...." and it stops again.

What can I do?

Or is there a better way to index a directory with so many files? We want also to reindex this directory one time every day.

By the way: where is the file "jetty-http.xml" to get access to SOlr remote admin from an other computer?

Many thanks!

**Comment by rusty9283** [comment]
Sorry It was a server problem.

**Comment by Mandalka** [comment]
"Indexing new file" is not the perfect label, since in this step not indexed / changed / new files are added to the queue. Document processing and indexing is done after that parallel in background, which takes much more time.

I'll change the label in https://github.com/opensemanticsearch/open-semantic-etl/issues/91
