### ISSUE TITLE
open semantic search server - FILEMONITORING don't work

### ISSUE THREAD

**Issue by rusty9283** [opensemanticsearch/open-semantic-search#189]
Hello!
When I trie filemonitoring via terminal:
opensemanticsearch-filemonitoring /mnt/

nothing happens.

I also tried over GUI:
![grafik](https://user-images.githubusercontent.com/50769525/60575389-bda8b800-9d7b-11e9-8a3f-e51498a84998.png)

![grafik](https://user-images.githubusercontent.com/50769525/60575429-d022f180-9d7b-11e9-9df7-230b9910d217.png)

but nothing will be indexed.

Can someone help me please?

Many Thanks!

**Comment by Mandalka** [comment]
The command line tool opensemanticsearch-filemonitoring works only if the filesystem is local on the server / the server or service (like Samba) is writing / changing files itself, but not if mounted an remote filesystem over network where writing the filesystem occurs on other / remote server.

The UI is not for file monitoring but adding crawling tasks.

If you want filemonitoring work on another Linux Server than the server of the search engine, you can use the "Filemonitoring remote" tool, which adds changed file to a remote search server document processing queue.

If not the case here but bug, please reopen.

**Comment by rusty9283** [comment]
Thank you for your fast response!
Can you please help me a bit with the "Filemonitoring remote" tool?
Where to download and how to install and configure?

MANY THANKS!

**Comment by Mandalka** [comment]
Best/most flexible way to index/recrawl directories from an other server is to

mount the remote directory by a network file system (like NFS or SSHFS and other Linux standard ways) to the local filesystem

and setup a cron job with
opensemanticsearch-index-dir /mnt/mydirectory

Filemonitoring (or filemonitoring remote i'll upgrade next days and answer other issue) can be done additionally to have not to wait for this recrawls, which should run from time to time, since filemonitoring sometimes can miss file changes.

**Comment by rusty9283** [comment]
I have tried your suggestion with "opensemanticsearch-index-dir" and mounting the remote directory and it works great except for one thing:
**If a file will be deleted - it will not be deleted from the index.**
Can you help me with this "issue"?

Many thanks!
