### ISSUE TITLE
Nothing really works

### ISSUE THREAD

**Issue by cocabonga** [opensemanticsearch/open-semantic-search#192]
Ok, first of all I want to let everybody here know that I tried to approach the whole open source and therefore Linux world in a neutral way, without prejudice or bias. But my experience so far get’s me to a point where I’m 5 minutes away from returning to my good old windows for good.

So here’s what I’ve done so far:

•	Installed Virtual box (Runs on  WIN7 64)

•	Downloaded “open-semantic-search-vm_19.06.14.ova” search appliance, since I wanted to be able to open the web interface across my LAN.

•	Imported the appliance

And that’s where the issues started already. In the documentation at https://www.opensemanticsearch.org/doc/admin/install/search_appliance
it says that one needs to add the shared folders containing the files to be indexed. I’d appears obvious that one needs to provide a mounting point in the guest file system, which is also displayed in the sample picture. I was looking around in the guest file system (using the little Linux knowledge I have) , trying to locate the displayed folders, but they’re just not there. There is a /home folder but there is no

/home/nutzer/dokumente and no
/home/nutzer/index

There is no /nutzer/ at all. So where on earth should I mount my content folders to, when the suggested folder are not even there?

I ended up trying to mount a folder into /home/

I fired up the VM and pointed my browser to “[local host IP]/search” as instructed.  The search home came up. So the first thing I did was clicking on datasources -> files and directories -> add new file or directory and entered /home/ as the path. I clicked index now and that was it. Nothing happened. No action, no error message , nothing. I often as I click on “index now” it just says “File or directory added to queue”. I then clicked on “show running and open imports and analysis tasks (ETL tasks)” only to be taken to the link “http://localhost:5555/tasks”  which obliviously cannot work, as it point to to local IP address of the host, so I changed “localhost” to my to guest local IP leaving the port number and the directory (tasks) the way it was but that too resulted in a connection error….

The current status is still the same. Indexing does not start, no error message…

How do I get this whole thing to work ???

**Comment by PeterausMG** [comment]
Hello Cocabonga,
I am not an expert, but have tried to understand your problem. Because I work with the server variant, I had to install virtualbox on Win10 pro and load the latest ova file.
After the start of Opensemanticsearch I was able to change the settings of Virtualbox and add under „Gemeinsame Ordner“ (German interface) the directory where my test data is located. The indexing could then easily start on the web interface of OSS, all files contained in this directory and the subdirectories were recorded. I did not need Linux knowledge for that.
I hope this helps you further.

Peter

**Comment by DieGoldeneEnte** [comment]
The problem with “show running and open imports and analysis tasks (ETL tasks)” linking to localhost has apparently just been fixed [in the open-semantic-search-apps repository](https://github.com/opensemanticsearch/open-semantic-search-apps/issues/55).
Concerning the "add new file or directory" not doing anything: I have a similar experience. I noticed adding files via the terminal works. At the moment I think there might be permission problems, because I want to have the files in a network share and not in the local home-directory. Maybe someone who has a working setup knows more. (Also I wouldn't add the /usr/share/doc to the index for testing, because there are too many files and it just ends up slowing the machine down)

**Comment by Mandalka** [comment]
Seems adding tasks to queue by datasources web UI in the server VM (most using commandline or commandlinetools by cron for server installations) is indeed buggy (Open Semantic ETL service worker does not process this tasks): https://github.com/opensemanticsearch/open-semantic-search/issues/196.

Another issue based on dependency hell of new verions of libs is fixed: https://github.com/opensemanticsearch/open-semantic-search-apps/issues/57.

There will be a new release next days.

**Comment by Mandalka** [comment]
Closing the issue, since https://github.com/opensemanticsearch/open-semantic-search-apps/issues/57 (the HTTP API calls failed if using different IPs to access the server) and https://github.com/opensemanticsearch/open-semantic-search/issues/196 (workers didnt process the tasks, if Rabbit MQ message queue name not configured) solved/ Apache/RabbitMQ queue names now preconfigured.
