### ISSUE TITLE
Some word documents not indexed properly - text body not accessible to the search engine

### ISSUE THREAD

**Issue by Akhanaten** [opensemanticsearch/open-semantic-search#194]
Hi

I have the desktop version installed on my system with the intention to be able to tag a large database of word documents and find reference across the whole database. So far so good but as I'm running tests with a subsection of documents (600-700) I'm finding that some of them won't be properly indexed as the search engine can't access the text body. On search these documents merely return results in the document title but nothing of the text body and the preview tab is empty. However I am able to open them directly through Libre Office, so there can't be a problem with permissions. 

It works fine for the majority of documents so I'm at a loss what the difference is.

Any help would be greatly appreciated

**Comment by Mandalka** [comment]
Are there ETL errors (you can preview the document where you find the subtab "ETL") for this kind of false-empty documents?

If not confidential, can you send me such an document which is previewed "empty" as email-attachment?

**Comment by Akhanaten** [comment]
Hi Markus,

Thanks for the quick response!

Unfortunately the documents are confidential, so I can't send them. However
I had a look under the 'ETL' tab. There is several warnings there that
might be the problem, but I'm not sure which one would be the relevant one.
I'm pasting it here:

*etl_enhance_extract_hashtags_b*:
1

*etl_enhance_file_mtime_b*:
1

*etl_enhance_contenttype_group_b*:
1

*etl_enhance_path_b*:
1

*etl_error_enhance_rdf_txt*:
'content_type_ss'

*etl_enhance_extract_text_tika_server_b*:
1

*Failed tasks while import & analysis (ETL)*:

•    enhance_extract_text_tika_server

•    enhance_contenttype_group

•    enhance_warc

•    enhance_zip

•    enhance_rdf



*etl_enhance_rdf_b*:
1

*etl_enhance_mapping_id_b*:
1

*etl_enhance_rdf_annotations_by_http_request_b*:
1

*etl_clean_title_b*:
1

*etl_enhance_csv_b*:
1

*etl_error_enhance_extract_text_tika_server_txt*:
'latin-1' codec can't encode character '\u2019' in position 80: ordinal not
in range(256)

*etl_enhance_warc_b*:
1

*etl_enhance_pst_b*:
1

*etl_error_txt*:

•    'latin-1' codec can't encode character '\u2019' in position 80:
ordinal not in range(256)

•    'content_type_ss'

•    'content_type_ss'

•    [Errno 13] Permission denied:
'/media/sf_index//opensemanticetl_enhancer_zip_0dd84bc1f40b4d144f86fd50d9c9dc3f'

•    'content_type_ss'



*etl_filter_file_not_modified_b*:
1

*etl_enhance_multilingual_b*:
1

*etl_error_enhance_warc_txt*:
'content_type_ss'

*etl_error_enhance_contenttype_group_txt*:
'content_type_ss'

*etl_enhance_regex_b*:
1

*etl_error_enhance_zip_txt*:
[Errno 13] Permission denied:
'/media/sf_index//opensemanticetl_enhancer_zip_0dd84bc1f40b4d144f86fd50d9c9dc3f'

*etl_enhance_detect_language_tika_server_b*:
1

*etl_enhance_zip_b*:
1

*etl_enhance_entity_linking_b*:
1

**Comment by Akhanaten** [comment]
Obviously there is several warnings of permissions denied, but how can I resolve this?

Thank you for your help.

**Comment by Mandalka** [comment]
The permission warnings are from some plugins, missing tmp directory with permissions, will fix that, but its not the main problem here.

Thanks for the status/error messages. The text could not be extracted since the Tika plugin for that failed.

The problem seems to be special chars in file names, so they could not be send by HTTP to Text extraction by Tika done by Tika-Python called by Open Semantic ETL (one of them seems to have a problem with charset of filename).

Maybe problem in Tika-Python or Open Semantic ETL or charset settings in the VMs Debian OS.

Which OS or if Linux which filesystem do you use to run the VM?

Can you add a simple textfile with content "Test" and using one of the filenames which doesn't work (adding .txt at end) which should have the same problem/error and zip this file and send it to me/some emailaddress of open semantic search, so i can debug which special chars or settings lead to this bug? If there are confidential infos in file name, you can change/remove all confidential infos with chars 0-9 and a-z and A-Z, but please not delete special chars from filename, which seem to cause the problem.

**Comment by Akhanaten** [comment]
Again thanks for the quick response, that is helpful.

Looking at all documents that report the tick server error during ETL process there are indeed special characters in all of them. It seems to be either one of 3 different characters that appear in all of these document, namely:   **'** as in **it's** ,   **–** an extra long dash  and  **é** apostrophes over French words. I'm still attaching .txt docs with these characters in.

A further question, once the troublesome special characters are identified, will it be enough to remove them from the title for the engine to re-index upon next opening or are there special measure to prompt an re-indexing?

Thank you.



[xxxx It’s xxxxx.txt](https://github.com/opensemanticsearch/open-semantic-search/files/3412429/xxxx.It.s.xxxxx.txt)
[xxxxx  –  xxxxxxx.txt](https://github.com/opensemanticsearch/open-semantic-search/files/3412430/xxxxx.xxxxxxx.txt)
[xxxxx é xxxxxx.txt](https://github.com/opensemanticsearch/open-semantic-search/files/3412431/xxxxx.e.xxxxxx.txt)

**Comment by Akhanaten** [comment]
Hi again,

I can confirm it is those special characters in the document title that prevent the according document to be indexed. Changing the document titles and the re-indexing via ‘Activities’ -> ‘Index documents’ will lead to correct indexing.

The only slight hick up now is that the old document is not being deleted, so upon searching something in the title of these documents they now appear twice, once as document title only and once as fully indexed document. It would be neater for a re-index to delete all files that are not present in the 'shared folder' anymore, or at least for that to be an option.

**Comment by opensemanticsearch** [comment]
Seems like tika-python had an bug with special chars in file names: https://github.com/chrismattmann/tika-python/pull/222

Next Open Semantic Search release will use newest tika-python release.

**Comment by Akhanaten** [comment]
Thank you for your response. Yes it was indeed the special characters that
caused the problem, mainly the symbols   '    and a long dash that was
inserted by word autocorrect. So some aspect of the engine was not able to
read those filed. They were however neatly listed under the ETL errors and
when going back to those files and amending the titles to not include such
characters anymore and re-indexing open semantic search was able to read
and index those documents without a problem. So the issue has been
resolved, thank you for your help.

**Comment by Mandalka** [comment]
New release is upgraded to new Python-Tika release, so indexing files with special chars in filename could work better without changing filenames even if i could not reproduce it by tests with special chars in German or French (but my OS is configured to UTF8 correctly)

Please reopen if yet problems (maybe some bugs with encoding in Open Semantic ETL in other OS environments or charsetconfigs instead of Tika-Python).
