### ISSUE TITLE
how to uninstall all the packages installed by open-semantic-search

### ISSUE THREAD

**Issue by pramod2157** [opensemanticsearch/open-semantic-search#213]
I have installed open-semantic-search using deb file.
I created an index file. I deleted the index file using opensemanticsearch-delete command.

The server is consuming all my resources.
I tried apt purge open-semantic*, opensemantic* and other variations as well. Iinstalled some of the packages like solr...
But still it is consuming all my resources.
Please check the below output of top:
![opensemanticsearchusage](https://user-images.githubusercontent.com/13517409/68368253-aa5c8d80-015d-11ea-8813-4b4dc604fcb3.png)
All the processes, solr, apache, neo4j...everything is created by opensemanticsearch.
please help me on priority

**Comment by Mandalka** [comment]
It consumes resources not despite you deleted the index but because you did it, so its reindexing (extraction, expensive OCR and NER by machinelearning) all the files you configured.

If you want to deinstall, you have to stop services and disable for next boot (which will be automatically done after next package release by only uninstalling the deb (last command)):

systemctl disable opensemanticetl-filemonitoring
systemctl stop opensemanticetl-filemonitoring

systemctl disable opensemanticetl
systemctl stop opensemanticetl

systemctl disable tika
systemctl stop tika

systemctl disable spacy
systemctl stop spacy

systemctl disable neo4j
systemctl stop neo4j

systemctl disable solr
systemctl stop solr

and after that deinstall the package by for example (as root or by sudo)
dpkg --remove open-semantic-search

**Comment by Mandalka** [comment]
After stopping solr you can additionally remove its binaries from /opt/ which will not be done by deinstalling open semantic search packages, because installed by the Solr installer.

**Comment by pramod2157** [comment]
I killed all the process. and then deleted all the files which the system shown me for below command:
sudo find / -name opensem*

**Comment by Mandalka** [comment]
Since there are services not matching this filenames like spacy, tika-server or solr, you should use the commands i described before, to disable all of them (which even if not used (so your load is not high anymore)) would consume some RAM.
