### ISSUE TITLE
Does not install cleanly on Debian 9.9

### ISSUE THREAD

**Issue by NetwarSystem** [opensemanticsearch/open-semantic-search#229]
I have been working on Open Semantic Search stuff for the past few days and it's been very frustrating. The Desktop Search OVA isn't right and it took hours of frobbing in order to get this procedure written, and it doesn't make all the features work.

http://netwarsystem.com/2019/07/13/coaxing-open-semantic-server-into-operating-condition/

Does this help in terms of quality control for the next release?

**Comment by mosea3** [comment]
Hi,
I can‘t dip further into this, because apparently there is something with with the URLs you keep posting here.
Both of them return a 404 Error so far.

best regards


Andy

Von meinem iPad gesendet

**Comment by opensemanticsearch** [comment]
Since there was related work on cleaner/easier more automated installation while migration to new Debian stable release where more such dependecies are defined explicitly and most of the described issues seem to work after the migration work (at least for Debian 10) without manual installations of underlaying dependencies, i close this issue on the deprecated Debian release.

Its a good idea not to install custom neo4j, if yet installed from other source.

To prevent such dependency hell scenarios in future, i opened the new issue [integration tests](https://github.com/opensemanticsearch/open-semantic-search/issues/241).
