### ISSUE TITLE
Extract phone numbers

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#246]
Add the regex config phone.tsv and facet config for facet phone_ss to out of the box default setup.

**Comment by Mandalka** [comment]
Regex now in git in https://github.com/opensemanticsearch/open-semantic-etl/blob/master/etc/opensemanticsearch/regex/phone.tsv

**Comment by Mandalka** [comment]
Facet phone_ss will be automatically added to facets config on upgrades by https://github.com/opensemanticsearch/open-semantic-search-apps/blob/master/src/thesaurus/migrations/0010_phone.py

**Comment by Mandalka** [comment]
Todo: Activate this regex config in /etc/opensemanticsearch/etl but maybe i'll add it to own plugin, since have to clean for filter facet and aggregations in a plugin (which is more generic than in Solr, fe if export to elasticsearch) to only nummeric input, so
+49-30-12345 and +4930-123-45 will result to same value / filter +493012345

**Comment by Mandalka** [comment]
Moved extraction of phone numbers to own plugin https://github.com/opensemanticsearch/open-semantic-etl/blob/master/src/opensemanticetl/enhance_extract_phone.py which will additional clean special chars from extracted patterns and add such normalized numbers to better filterable/aggregateable facet phone_normalized_ss additional to unfiltered phone_ss which will be shown as better readable/judgable snippet.

**Comment by Mandalka** [comment]
Added new plugin to default config https://github.com/opensemanticsearch/open-semantic-etl/blob/master/etc/opensemanticsearch/etl
