### ISSUE TITLE
Issue indexing website / Unable to access queue?

### ISSUE THREAD

**Issue by DennisNDean** [opensemanticsearch/open-semantic-search#250]
This is a fresh install of version 20.01.15 on Debian. 

As a test, I added a website URL in /search-apps/crawler/.
It adds it to the list as crawler 1 under All Websites. I then hit "Index now".
After leaving it for a while, nothing comes up in Search. 

I set "URL of Flower task monitoring UI" to my server (a DigitalOcean droplet) IP address, as http://XX.XX.XX.XX:5555

However, http://XX.XX.XX.XX:5555/tasks is unresponsive. 

EDIT:
I don't know if this is helpful but this is in my Apache error log any time I hit "index now":
[Thu Jan 16 23:34:35.656300 2020] [wsgi:error] [pid 27337] [remote XXXX] /usr/lib/python3/dist-packages/django/db/models/fields/__init__.py:1430: RuntimeWarning: DateTimeField Crawler.last_imported received a naive datetime (2020-01-16 23:34:35.650937) while time zone support is active.
[Thu Jan 16 23:34:35.656346 2020] [wsgi:error] [pid 27337] [remote XXXX]   RuntimeWarning)

**Comment by Mandalka** [comment]
The warning in apache log is not the problem.

The tasks monitoring UI is not responsive, because yet not out of the box started by deb package and you have to install and configure (it has to be configured safe, so not everyone from your network can access it) flower (f.e. by pip3 install flower).

But even without that you can maybe see whats the problem with crawling in /var/log/daemon.log where the daemon / service opensemanticetl will log its output like scrapy crawler log / status messages.

Please write an email or reopen this issue if not clear whats the problem with help of this log.
