### ISSUE TITLE
Error on Search Page

### ISSUE THREAD

**Issue by hiwire03** [opensemanticsearch/open-semantic-search#277]
Could anyone help me out with an error message I am getting on the home search page?

Error:
Apache_Solr_HttpTransportException: '400' Status: Bad Request in /usr/share/solr-php-ui/Apache/Solr/Service.php:338 Stack trace: #0 /usr/share/solr-php-ui/Apache/Solr/Service.php(1170): Apache_Solr_Service->_sendRawGet('http://localhos...') #1 /usr/share/solr-php-ui/index.php(1438): Apache_Solr_Service->search('*:*', 0, 10, Array) #2 {main}

The following is the sequence of actions I did prior to this error.

(a) On the "Add new named entity, name, word or concept" page I clicked the "[Manage target facets / fields / properties]" 
(b) The above link landed me on the page "Select facet to change" under the Django administration page  http://localhost/search-apps/admin/thesaurus/facet/
(c) In the "Add facet" option I typed "Subject" under Label and "Facet", left the rest as default and clicked the "Save" button.

**Comment by Mandalka** [comment]
Seems you added a facet fieldname ("subject"), which is not in the Solr search index schema, so Solr rises an error.

You can delete the facet in /search-apps/admin/thesaurus/facet/ or if you want to add this facet rename the facet fieldname (not label) to subject_ss instead of subkect so the field will be handled because of suffix _ss as dynamic fieldname of type strings Solr can handle without adding it to the schema manually.
