### ISSUE TITLE
Upgrade packages to Django 2

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#303]
To get rid of two different branches for Django 1 and 2 (code upgrade yet done but releases yet in seperated branch) because Debian stable yet uses Django 1, try to install Django 2 from Debian backports. So hopefully only one branch needed for Pip, Debian stable and Ubuntu LTS.

**Comment by Mandalka** [comment]
Seems its easier for users, if for the rest of the months before release of new/next Debian Bullseye there will be yet two branches and you do not have to add additional repos in Debian for an installation but we use Ubuntu as base for docker, so building docker containers should work without managing branches.

**Comment by Mandalka** [comment]
The Docker container with Django environment now uses current Ubuntu 20.04 LTS, so the main branch can be used out of the box (not after next Debian release) as base for building Docker images without having to checkout alternate branches. Maybe switching back to Debian after next release next year.

**Comment by Mandalka** [comment]
Bad news (breaking issue https://github.com/opensemanticsearch/open-semantic-search/issues/325 which i did not realize earlier because (old) Debian buster image in Docker caches) now good news:

After release Debian 10.6. (newest update of Debian buster/stable) and its updated Django minor release it is now possible to use the branch / code which was made ready for Django 2 / Ubuntu some months ago so i could remove separated branch for Debian and Ubuntu.

So changed Docker apps container back again to same release (currently Debian buster), like used by our other services.
