### ISSUE TITLE
Document index does not rebuild automatically after adding new tag

### ISSUE THREAD

**Issue by nikhilbhalwankar** [opensemanticsearch/open-semantic-search#356]
I am facing issues related to newly added annotation. I followed below steps,

1) Go to annotations option
2) add new annotation of type tag
3) attach tag to the document
4) search by new tag does not work unless I delete index for that document and again create index.

I have the same issue for latest .deb package as well as latest .ova also. Kindly let me know what can be done so that the rebuilding happens automatically.

**Comment by Mandalka** [comment]
Reason: add aproach in export_to_index(uri) in src/open-semantic-search-apps/src/annotate/views.py doesn't work because of single valued Open Semantic ETL metadata.

Solr error log while tagging a doc:

org.apache.solr.common.SolrException: ERROR: [doc=file:///usr/share/doc/apt-utils/NEWS.Debian.gz] multiple values encountered for non multiValued field etl_enhance_multilingual_time_millis_i: [2,&#8203; 0]

**Comment by Mandalka** [comment]
Closing this issue since same as #366 (more debug infos and comming fix there).
