### ISSUE TITLE
Annotations are not saved in Solr

### ISSUE THREAD

**Issue by vucod** [opensemanticsearch/open-semantic-search#366]
I'm not able to use the annotation on a fresh docker installation.

Annotations (notes and tags) are saved in Django but they are not accepted by Solr for these reasons:

- multiple values encountered for non multiValued field ...
- cannot change DocValues type from NUMERIC to SORTED_NUMERIC for field ...

It seems to be for a lot of fields:

- etl_enhance_multilingual_time_millis_i
- etl_time_millis_i
- etl_enhance_rdf_annotations_by_http_request_time_millis_i
- etl_enhance_mapping_id_time_millis_i  
- etl_filter_blacklist_time_millis_i   
- etl_enhance_path_time_millis_i
- etl_export_solr_time_millis_i
- etl_export_queue_files_time_millis_i
- etl_count_images_yet_no_ocr_i
- etl_enhance_extract_text_tika_server_time_millis_i
- etl_enhance_detect_language_tika_server_time_millis_i
...

Basically all fields following the dynamic field *_i.

I tried to change the properties of the dynamic field *_i by adding multiValue=True and DocValues=False in the Solr UI but it didn't work.

What do you think is causing the issue? Is it a wrong configuration of the schema of Solr or it is the ETL component that is sending not correctly formatted data?

This bug means that it currently difficult to do some document managements as no filtering on tags are possible.

Possibly related to https://github.com/opensemanticsearch/open-semantic-search/issues/356

Thanks for your help and  thanks for you work on this nice tool!

Vucod

used https://github.com/opensemanticsearch/open-semantic-search/blob/master/docker-compose.yml from commit 
https://github.com/opensemanticsearch/open-semantic-search/commit/e68e9a2e526a6abd4a4a14f1989d5eaac83fe62d

**Comment by Mandalka** [comment]
Reason: "add" aproach in export_to_index(uri) in src/open-semantic-search-apps/src/annotate/views.py doesn't work because of single valued Open Semantic ETL metadata.

Solr error log while tagging a doc:

org.apache.solr.common.SolrException: ERROR: [doc=file:///usr/share/doc/apt-utils/NEWS.Debian.gz] multiple values encountered for non multiValued field etl_enhance_multilingual_time_millis_i: [2,​ 0]

Have to remove additional Open Semantic ETL metadata if doing an add operation instead of default set operation on Solr document.

By bcddcb2 such an error will raise an exception up to UI.
