### ISSUE TITLE
Upgrading the Tika server version to 2.x

### ISSUE THREAD

**Issue by wsldankers** [opensemanticsearch/open-semantic-search#389]
Hi,

As you may have noticed we (@sdinten and me) are trying to get the docker-compose based version up and running, by fixing the small issues that inevitably pop up when a complicated project like this is updated to stay with the times. We've already submitted a number of pull requests that deal with these small issues, I hope they are useful.

One thing that is proving slightly trickier is the Tika Server upgrade. The `X-Tika-OCRTesseractPath` header has been removed from the server (probably in response to CVE-2018-1335). Looking at the Tika Server source code I see no other reasonable way to pass options to select a specific tesseract backend implementation.

One possible alternate course of action is to run a number of Tika Server instances, each with a different tesseract backend: normal, caching and fake-caching. I was able to implement this in docker-compose with fairly minimal changes and I could probably also port this to the vm/.deb setup using systemd service instances.

Do you think this is a viable approach? If so I can prepare and submit a PR.

Cheers, and thanks for Open Semantic Search!

**Comment by Mandalka** [comment]
Thank you very much for all the PRs!

Seems we need multiple Tika instances if "OCR later" is on :-/

Thanks for research of the current possibilities of the former bypass and if yet config parts done, please contribute, since i planed to work on same issue next weeks.

Note: Further work on OCR config (with the tesseract-ocr-cache repo) must include/base/bump on the improvements of the tesseract-ocr-cache by @g-braeunlich in https://github.com/opensemanticsearch/tesseract-ocr-cache/pull/3 i delayed to merge (i did now).

**Comment by Mandalka** [comment]
Seems with the new Tika releases the "OCR later"-feature needs two Tika configs (and instead of setting the header option tesseract_fake in request header to use the other Tika server url by the tika ETL plugin).

One for tesseract_cache and one for tesseract_fake, which ideally both have acces to same cache (tesseract_fake reasonly).

I wrote some quick and dirty documentation about how the wrappers work to https://github.com/opensemanticsearch/tesseract-ocr-cache/blob/master/README.md

**Comment by wsldankers** [comment]
Yep, this is exactly how I implemented it. It's just the docker-compose setup though; it would need a (small) bit of additional work to adapt this to the VM.

**Comment by Mandalka** [comment]
Would be nice, if you could share the yet done parts and i do some further work if needed, since i try to release new Tika 2.x based release / packages within next one or two weeks.

**Comment by Mandalka** [comment]
Thank you very much for https://github.com/opensemanticsearch/open-semantic-search/pull/393 !
