### ISSUE TITLE
Can't download

### ISSUE THREAD

**Issue by Redfull** [opensemanticsearch/open-semantic-search#41]
Stupid question but the files for open-semantic-search desktop are nowhere to be found (error 404 on the official site)
Thanks !

**Comment by opensemanticsearch** [comment]
New releases today and available as Debian packages. The VMs will follow. Its because of file size (2 GB) so upload of nightly build is not up yet. Will close the issue when the new VM is available on the download server, too. But be aware, its beta with some important and maybe yet incomplete changes under the hood / on the search index schema. Next release next days/next week.

**Comment by Redfull** [comment]
Thanks !

**Comment by opensemanticsearch** [comment]
English VM is available for download. German VM next hour.
