### ISSUE TITLE
No indexed file with Docker image

### ISSUE THREAD

**Issue by davidvilanova** [opensemanticsearch/open-semantic-search#421]
Hi,
I´m running the docker image as suggested (under linux)

docker-compose up

I try to index a local folder(linux) and no files are indexed. For instance, i have a documents folder that contains two files, test.docx and test.pdf

See the output from the log

<img width="879" alt="image" src="https://user-images.githubusercontent.com/11404840/159175420-46998af7-f66f-4e8a-a9f7-d73a00f2c332.png">

The log does not show any significant message as follows:

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/11404840/159175478-d8286fab-148c-4d2f-8fb4-7e32e20aa99d.png">

Looks like no file is indexed. What is the problem ??

**Comment by rickcecil** [comment]
Oddly, I am having the same issue. I say oddly because this has previously been working. I had indexed several thousand files, but wanted to setup some blacklists before going further. 

To accomplish this, I added this volume to the etl section of docker-compose file

`./blacklist:/etc/opensemanticsearch/blacklist`

Then, created a directory with some test files to index. This directory has a handful of zip, PDF, docx, jpg, and MP4 files. I also incuded a .DS_Store file.

I had initially added zip and DS_Store to the "blacklist-url-suffix" file. As expected, it did not index either file. However, it also didn't index the other files either. 

Flower shows that the files are getting processed with runtimes varing between .1 and 5 seconds. However, the Result for each file was "None." I am not sure exactly what that means. I am still poking around on the Flower site to figure that out.

My initial thought was that it didn't like the blacklist directory/files being mounted to an external volume. However, when I removed the Zip, the zip file was actually indexed, so it seems to be reading the host mounted blacklist volume just fine. As a side note, when I remove the .DS_Store file, it started showing in Flower (it previously was skipped -- as expected) but also had 'None' as the result.

**Comment by rickcecil** [comment]
Looks like I was mistaken. My files are showing up in the index. When I search for the files, they are there. I was expecting them to show up in the "Newest Documents". However, "Newest Documents" seems to be keying off creation date of the file rather than the date it was added to the index.

**Comment by davidvilanova** [comment]
DO you have to write a particular setting in docker-compose to allow the docker image to access the host machine ??

**Comment by davidvilanova** [comment]
Hi @rickcecil ,
You are right. I didn´t specify the data path in docker-compose.yml. Just added it and it works. I though the /(root) partition was mounted by default.

Thanks !!!
