### ISSUE TITLE
NOT working!

### ISSUE THREAD

**Issue by DJProject** [opensemanticsearch/open-semantic-search#438]
All installations tested:
.DEB file downloaded from webserver,
Build .DEB file from source with instructions on GIT

NOTHING works!

**Comment by OzInFl** [comment]
HEY TRY this! I beat my head against the wall with the deb and ubuntu installations, I finally installed ubuntu 22 on a server and when it failed complaining about APT user perms, I did the following to get it to work. (http://localhost/search = blank page  and http://localhost/flower working fine..)   Im not sure if its all necessary but it did the trick...

After the failed ubuntu   .deb file install....

sudo chmod 777 open-semantic-search_22.03.04.deb

pip3 install Django==3.2
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install php7.4
sudo apt-get install php7.4-cli php7.4-common php7.4-json php7.4-opcache php7.4-mysql php7.4-mbstring  php7.4-zip php7.4-fpm php7.4-intl php7.4-simplexml
sudo a2dismod php8.0  or (sudo a2dismod php8.1)  depending on version
sudo a2enmod php7.4
sudo systemctl restart apache2


All working from there as far as i know, I havent started indexing yet, but all the pages work like they should.

**Comment by ingenika** [comment]
After install _tesseract-ocr_by `apt-get install tesseract-ocr`
It works

**Comment by NetwarSystem** [comment]
About two years ago I took the time to build every component by hand so I could better support Open Semantic Search. I had never done more that _apt install_ prior to that, so I had a real learning curve.

A thing I just noticed recently is that the erratic behavior of Solr on startup can be corrected by increasing file handles and processes in /etc/security/limits.conf. This is probably crazy overkill, but I have ArangoDB and Elasticsearch running in a couple places, so I just standardized on this setup.

```
elasticsearch	-	nofile		300000
root		-	nofile		300000

*		hard 	nofile 		300000
* 		soft 	nofile 		300000

*               hard    nproc           65000
*               soft    nproc           65000
```

Flower in the past has had a minor issue, I forget the exact details, but it's something like ... the hostname not being in a piece of Python code for the main user interface? If you search closed topics here you should find a solution to that.

I'm still running the open-semantic-search-vm_21.01.17.ova, I use it under VirtualBox, and then used Linked Clones to create multiple instances w/o burning disk space. My workstation has ZFS so I can snapshot a dataset (ZFS word for directory tree) when I make changes, because OSS can be touchy. If I had not had the snapshot/restore capabilities, so I can checkpoint the system before each major change, I'd have given up long ago. If you're new to OSS, I think it would be very worthwhile to spend a little time learning ZFS, and then getting into OSS - that investment at the front end will pay ongoing dividends as you learn.

**Comment by Mandalka** [comment]
(External) Dependecy hell cause why new installations not working on Debian stable since some time: #443 (new packages tomorrow).

Ubuntu: Had no time yet to check/adjust lib versions/compatibility on new Ubuntu releases/releasing a Ubuntu package.

**Comment by Mandalka** [comment]
Dependency hell isssue #443 is fixed and should be the cause why since some time nothing works.

If not fresh installation but repairing the system where "nothing works" remove the pip packages django-import-export and django first.

Please reopen, if yet not working.
