### ISSUE TITLE
Replace "Trigger File Monitoring" packages by new tool from "File Monitoring Remote"

### ISSUE THREAD

**Issue by clamor** [opensemanticsearch/open-semantic-search#7]
There are two Ubuntu .deb packages ( opensemanticsearch-trigger-filemonitoring_15.06.26_all.deb and opensemanticsearch-trigger-filemonitoring-daemon_15.06.26_all.deb ) on http://www.opensemanticsearch.org/download/ which have a dependency on a opensemanticsearch-connector-files package in the DEBIAN/control file. Unfortunately I did not manage to find that package on the website.

**Comment by opensemanticsearch** [comment]
This dependency does not longer exist, since all connectors have been consolidated in the Open Semantic ETL package.

This old file monitoring packages (mainly shell scripts starting command line tool) will be replaced by the newer and more flexible/powerful Python code base from "Trigger Filemonitoring Daemon Remote" which supports removing deleted files from index, too.

Will be done for new releases in two or three weeks, when the (yet implemented) Celery queue for the API is integrated out of the box, so that many new files will be indexed parallel in batch mode and not all files parallel at once (needs too much RAM, if many new files in very short time).
