### ISSUE TITLE
indexing directory not working

### ISSUE THREAD

**Issue by roasting223** [opensemanticsearch/open-semantic-search#82]
Since version 2018-01-19, indexing directories is not working any more.

System: Open Semantic Search Server 18.01.26 on Debian 9

Using the -v flag for opensemanticsearch-index-dir shows for example:
Scanning directory: /xx/xx/xx
Scanning file: y.pdf
Adding file to queue: /xx/xx/xx/y.pdf
Sanning file: z.pdf 
Adding file to queue: /xx/xx/xx/z.pdf
...
(same for .html files)

After that, nothing happens and the files do not appear in the search.

opensemanticsearch-index-file works fine

Where else can i look for more hints on what exactly is not working?

**Comment by Mandalka** [comment]
Since for opensemanticsearch-index-dir after adding to the queue the analysis of files is done parallel for multiple files / on multiple CPUs by Celery workers tasks, the workers and so the system user "opensemanticetl" must have the right to read the files.

If you use opensemanticsearch-index-file the files are indexed in batchmode with the right of the user calling it, only the named entities recognition runs on multiple processors, since own microservice.

Please reopen, if this doesn't solve the problem.

**Comment by roasting223** [comment]
Thanks, that solved it!
