### ISSUE TITLE
Preview: Exclude etl processing status messages from metadata to own sub view / tab

### ISSUE THREAD

**Issue by opensemanticsearch** [opensemanticsearch/open-semantic-search#85]
In preview own sub view / sub tab for ETL processing flags and errors messages so sub view metadata not used additionally for ETL metadata

**Comment by Mandalka** [comment]
With new get_fields() we have a good base for that, since there is the parameter exclude_prefixes.

Have to change all ETL status, flags and errorlog fields of Open Semantic ETL plugins to prefix etl_ and exclude it in the preview subview "meta data" of search UI by exclude this prefix at call of get_fields().

**Comment by Mandalka** [comment]
Was implemented long time ago and extended to Tika processing fields by https://github.com/opensemanticsearch/open-semantic-search/issues/206
