### ISSUE TITLE
indexing directories very slow

### ISSUE THREAD

**Issue by roasting223** [opensemanticsearch/open-semantic-search#98]
as a follow-up to #82 
Indexing directories for me is very slow since the switch to celery worker tasks. I currently have it running in a Debian 9 Xen VM. If I assign one CPU core to the VM, indexing uses between ~5 and ~35% CPU in average, with very short peaks to 100%, taking forever to index a few 10.000 simple html files. 

If I assign more than one CPU, indexing frequently stops completely and only resumes on reboot. I already tried disabling Spacy mining, which did not make a difference. With the old indexing mechanism, CPU usage was always at 100%. 

Any hints or ideas what could be the problem?

**Comment by Mandalka** [comment]
Do you mean indexing of directories or recrawling (indexing new/changed files?)

Are there images with the HTML files ? Most resources needed for
- Deskewing plugin for OCR (uses many CPU ressources and doubles needed OCR ressources)
- OCR (for images in PDF the OCR plugin or for images Tika if tesseract installed on Tika Server)
- Named Entity Recognition by Spacy (default) and/or Stanford NER

Such plugins can be disabled or with new release in some weeks run later in background

- REcrawling of file directories. This will be solved by https://github.com/opensemanticsearch/open-semantic-etl/issues/40

- If you want to increase low CPU usage you can test to increase the count of parallel celery tasks if enough RAM for that.

I'll do some extended tests and documentation for scale options such next weeks.

**Comment by Mandalka** [comment]
After https://github.com/opensemanticsearch/open-semantic-etl/issues/40 with next release of packages, filters are applied before adding files to queue for much better performance of recrawl of indexed directories/files.

If it was not a recrawl:

The most resource hungry plugins like
- PDF OCR
- Descewing
- Named Entity Recognition by machine learning (Spacy)
can be disabled in /etc/opensemanticsearch/etl
- OCR of images by Tika (if there are images because not only HTML files but images downloaded, too) - therefore you have to uninstall tesseract to diable Tikas OCR

Imortant: disabling will only be applied if restarting the Open Semantic ETL celery workers (f.e. by reboot, since the Debian package yet has an problem for service opensemanticetl restart).

Most things will be runned parallel for multiple files if multiple processors, but maybe the spacy plugin run using spacy-services has to wait until another run(s) from parallel processes are done, since spacy sems use multiple cores but only for each file / doing processing of REST calls in batch mode.
